package rif_app;

/*
 * Clase para realizar la interfaz gráfica de la aplicación.
 */

/**
 *
 * @author Johance Castillo
 */
import javax.swing.JOptionPane;

public class InterfazGráfica extends javax.swing.JFrame {
Nro_de_chequeo nc = new Nro_de_chequeo();
    /**
     * Creates new form InterfazGráfica
     */
    public InterfazGráfica() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        grupo_botones.add(Venezolano);
        grupo_botones.add(Extranjero);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo_botones = new javax.swing.ButtonGroup();
        Salir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Cedula = new javax.swing.JTextField();
        Venezolano = new javax.swing.JRadioButton();
        Extranjero = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Resultado = new javax.swing.JTextField();
        Enviar = new javax.swing.JButton();
        Ayuda = new javax.swing.JButton();
        jLabelfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(450, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Salir.setBackground(new java.awt.Color(0, 0, 51));
        Salir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Salir.setForeground(new java.awt.Color(255, 255, 255));
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        getContentPane().add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 20, 70, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setText("Elija su nacionalidad:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        Cedula.setBackground(new java.awt.Color(0, 0, 51));
        Cedula.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Cedula.setForeground(new java.awt.Color(255, 255, 255));
        Cedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CedulaActionPerformed(evt);
            }
        });
        getContentPane().add(Cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 190, -1));

        Venezolano.setBackground(new java.awt.Color(51, 102, 255));
        Venezolano.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Venezolano.setForeground(new java.awt.Color(255, 255, 255));
        Venezolano.setText("Venezolano");
        Venezolano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VenezolanoActionPerformed(evt);
            }
        });
        getContentPane().add(Venezolano, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        Extranjero.setBackground(new java.awt.Color(51, 51, 255));
        Extranjero.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Extranjero.setForeground(new java.awt.Color(255, 255, 255));
        Extranjero.setText("Extranjero");
        getContentPane().add(Extranjero, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 140, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("RIF Generado:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 51));
        jLabel3.setText("Número de Cédula:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        Resultado.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Resultado.setForeground(new java.awt.Color(0, 0, 51));
        Resultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResultadoActionPerformed(evt);
            }
        });
        getContentPane().add(Resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 260, -1));

        Enviar.setBackground(new java.awt.Color(0, 0, 51));
        Enviar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Enviar.setForeground(new java.awt.Color(255, 255, 255));
        Enviar.setText("Enviar");
        Enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnviarActionPerformed(evt);
            }
        });
        getContentPane().add(Enviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, -1, -1));

        Ayuda.setBackground(new java.awt.Color(0, 0, 51));
        Ayuda.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Ayuda.setForeground(new java.awt.Color(255, 255, 255));
        Ayuda.setText("Ayuda");
        Ayuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AyudaActionPerformed(evt);
            }
        });
        getContentPane().add(Ayuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 80, -1));

        jLabelfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/blue.jpg"))); // NOI18N
        jLabelfondo.setText("jLabelfondo");
        getContentPane().add(jLabelfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    private void VenezolanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VenezolanoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VenezolanoActionPerformed

    private void ResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResultadoActionPerformed

    private void EnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnviarActionPerformed
        // TODO add your handling code here:
       
        
        
        
        if (Venezolano.isSelected() ){
        String SCedula = Cedula.getText();
                  
        int nro_cheq = nc.Cálculo_Nro_de_chequeo(SCedula);
        
        Resultado.setText("V-"+ SCedula +"-"+ nro_cheq );
                  
        }
        
        if (Extranjero.isSelected()){
        String SCedula = Cedula.getText();
                      
        int nro_cheq = nc.Cálculo_Nro_de_chequeo(SCedula);
        
        Resultado.setText("E-"+ SCedula +"-"+ nro_cheq );
                  
        } 
        if((!(Extranjero.isSelected())) && Cedula.getText().length()== 0 && (!(Venezolano.isSelected()))){
         JOptionPane.showMessageDialog(null,"Seleccione su nacionalidad e introduzca su número de cédula");
        
        }
    }//GEN-LAST:event_EnviarActionPerformed

    private void CedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CedulaActionPerformed

    private void AyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AyudaActionPerformed
        // TODO add your handling code here:
        Ayuda_Interfaz atrás = new Ayuda_Interfaz();
        atrás.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_AyudaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazGráfica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazGráfica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazGráfica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazGráfica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazGráfica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ayuda;
    private javax.swing.JTextField Cedula;
    private javax.swing.JButton Enviar;
    private javax.swing.JRadioButton Extranjero;
    private javax.swing.JTextField Resultado;
    private javax.swing.JButton Salir;
    private javax.swing.JRadioButton Venezolano;
    private javax.swing.ButtonGroup grupo_botones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelfondo;
    // End of variables declaration//GEN-END:variables
}
